### ISSUE TITLE
Editar el tema

### ISSUE THREAD

**Issue by jordic** [projectestac/xtecblocs#29]
Hola, estava intentant editar el tema del blog de l'escola de la meva filla, i no trobo per enlloc, com accedir a l'editor d'arxius que wordpress normalment té. 

Es una restricció que teniu posada?

Hi ha alguna manera de poder editar-lo.

Volia fer coses trivials, com tocar la fulla d'estils, o afegir una llista de posts a determinades pàgines.

**Comment by sarjona** [comment]
Hola Jordi!

Millor que ens facis arribar aquesta consulta a través de l'espai de suport de XTECBlocs: http://educat.xtec.cat/groups/group/show?groupUrl=blocs-a-l-aula

A més, si pots, aniria bé acompanyar-la d'alguna captura de pantalla de l'apartat on trobes a faltar aquest editor d'arxius (tot i que si et refereixes a l'editor del codi de les extensions ja t'avancem que està desactivat perquè el codi font és compartit per tots els blogs ;-) ).

Una abraçada i gràcies per la comprensió!
Sara

**Comment by jordic** [comment]
B, no, el codi font del blog no... Concretament jo vull tocar el codi font del tema, o crear-ne un de nou!

**Comment by toniginard** [comment]
Hola Jordi,

No es pot modificar el codi de cap part de XTECBlocs, cosa que inclou els temes. Tampoc podeu afegir temes ni extensions. El motiu és que el codi és compartit per tots els blogs i qualsevol canvi afecta a tothom.

L'únic tema que admet personalització és el tema XTEC, que és un tema pensat per ser modificat i, per això, l'estètica inicial no està treballada. D'altra banda, si només vols fer petits canvis a un tema pots provar de posar els estils dins d'un giny de tipus text.

Salutacions,

Toni
