### ISSUE TITLE
Aumentar el nombre d'articles per pàgina a 50

### ISSUE THREAD

**Issue by jmeler** [projectestac/xtecblocs#30]
En el tema gràfic fukusawa, aumentar el nombre d'articles a 50. És un tema basat en targetes, semblant a pinterest (mansory) que admet molts més articles per pàgina.

**Comment by sarjona** [comment]
Com és un canvi que només afecta als blogs de l'EPA, s'ha decidit que es canviarà només a la maqueta.

La @monicagrau va deixar-ho canviat ahir al blog que es fa servir de maqueta.
