### ISSUE TITLE
Els meus llocs, botó Afegeix 

### ISSUE THREAD

**Issue by jmeler** [projectestac/xtecblocs#36]
Al tauler apareix l'opció **Els meus llocs** i dins un botó per **afegir** 

![image](https://cloud.githubusercontent.com/assets/5380649/16686035/7718da9a-450f-11e6-99f4-453fb546fdce.png)

Des d'un CDA notifiquen que els dona error (sense permissos). Crec que el únic lloc per demanar un nou bloc és a blocs.xtec.cat al botó "Crea el teu bloc", oi? Si és així, amagar el botó al tauler.

**Comment by sarjona** [comment]
Amagar el botó o bé revisar-ho per tal que porti a la mateixa pàgina que fan servir ara els usuaris per crear blogs nous.

**Comment by toniginard** [comment]
El botó ja porta a la mateixa pàgina que fan servir els usuaris per crear blogs. L'error que apareix ("No teniu autorització per crear blocs nous.") és degut a que l'usuari que intenta crear el blog no és un usuari XTEC.

S'ha canviat el missatge per a que sigui més descriptiu: "Només poden crear blogs els usuaris XTEC". S'ha fet en el commit següent:

https://github.com/projectestac/xtecblocs/commit/9b82cb1a74b8dcb509863aaf44a86a969b028c38
