### ISSUE TITLE
Dades del docent al personalitzador

### ISSUE THREAD

**Issue by jmeler** [projectestac/xtecblocs#38]
Crear un **giny** **Dades d'usuari** on el docent pugui informar els següents camps: 

- Imatge (uploader d'imatge)
- Nom (input text)
- Cognoms (input text)
- Perfil curt (camp de text -només text, no html- amb 250 caracters màxim)
- Correu electrònic (input text)
- Web  (input text)
- Twitter (input text)

La idea es que al camp web pugin posar la seva web o blog, o bé un enllaç al seu linkedIn, about.me o facebook, etc.

A nivell gràfic, l'aspecte al frontend no ha de diferir molt de: 

![image](https://cloud.githubusercontent.com/assets/5380649/18709704/b170c31a-8001-11e6-9b58-09baf2323813.png)

**Observacions:** 
- Si el docent no afegeix informació en un camp, el camp queda amagat (i la seva icona associada, si n'hi ha).
- Projecte EPA (Entorn Personal d'Aprenentatge), aplica de moment només a XTECBlocs.
- No aplica a Nodes
- Per defecte s'afegeix com a imatge de la fitxa aquesta imatge: 

![nobody](https://cloud.githubusercontent.com/assets/5380649/18777999/637bfb8a-8172-11e6-831e-d34f87c57754.png)

- L'usuari pot esborrar aquesta imatge per defecte o pujar una de nova.
- Els icones: aprofitem els nadius de WordPress ([dashicons](https://developer.wordpress.org/resource/dashicons/))

**Comment by sarjona** [comment]
- Nom i cognoms tindran el mateix comportament que la resta de camps: si no s'especifiquen, no es mostraran. Per tant, de moment no s'afegirà el booleà.
- De moment només s'afegirà a XTECBlocs s'afegirà com a giny i estarà disponible per totes les aparences. Va bé @jmeler ?

**Comment by jmeler** [comment]
@sarjona Correcte, gracies sara. Edito la issue.

**Comment by jmeler** [comment]
Valorar la possibilitat de posar la imatge per defecte en format base64 (en lloc de tenir-la al sistema de fitxers). 

< img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAJ/ElEQVR4Xu2d4XXUOBDHJacAchWQVECoAKgAqCBY5ntCBUAFwHdsJxVAKrhQwYUKLlRwoYB47v152nt7xru2LMma2ZXfy6dYXmnmp9FopJG02vGnbdtDInqitT7puu5Ea32olDqyf+utv1VK3RLRXVEUN0R0o7X+Vpbl3S6LSO9i49q2hbJPtdZPlVInnm0EDNdFUVyWZXnj+S12xXcGAPR0pdQpEZ0P9O5Qgr/VWn9USgGGnbAM4gGwij+zigcESzx3FoRP0kEQDUDTNKdKKfTIpRTfhwtW4NwYc7kEdTF+QyQAbdseEVGrlMIYz+G51lqXZVnCkRT1iAPg8+fPL4qigPJT9fpNCr7ruq58/fr1V0kEiAKgrusPWms4eWwfIvpYVdUbthXsVUwMAHVdt1rrVxIES0QXVVWVEuoqAoC6rr9orV9IEOiqjlIgYA+ApJ7fB1QCBKwBaJoGU7wzST1/oK6fjDFs/Ra2AFhv/4tw5f+qftd1L7nODlgCYOf5fzGc6s3lEZHDxxzjBCwBaJrmT0ZBnrlK75e7NsY8C/WxUN9hB0Bd16+01gj07NxDRGVVVRecGsYKALt2//cOmf6+rjEUHHNaQGIFQF3X77TWbzn1kNB1IaL3VVW9C/3dud9jA8Ae9P6VjlhZATYA1HV9rrX+MJdkW+5KKfXc8xvRixPRm6qqEONI/rABoGkajP3Yq+f8ENFPInqFuXbTNHCysE+A83NjjHnMoYIsAMAePiLCvN/5IaLvRVE8XTlWiCF0XYcNnQ+cP7ZgARsXSL7HkAUAHiHfK6wQ9r3qQMNJbBxYhIi5AIDe77p798oYs3GFsGmaa6XUk9ha9Pg+i2EgOQDW+//HRZB9sz9UFt/tug67eNkOBVrrP1LHBJID4LroQ0Q/iqI4mSI4mx+A/XosIeCwSJQcANfgj9b6WVmWMO+THs4QcAgKJQegaRpsopw6d5/lODGG4NIYk3SbGwcAJjlrmOsXRXE0xfRv8AmQLsZtOPhmjEm6tZ0DAJMCQCHMpY0RfNVaP5o0fsR/KflMgAMANCZn396//n0768BiDIutZsaYpDpI+uNQTNM0owAgGTP0WInZB/L7tNYPxwCM+f8MwAQAYk2XOFiDDMAIAJj3V1U1a5Foas+1exAxLCy+iLT3ANR1jfXxbYGarSHfqUqe8t7SICwB91i7OfgAW6eBIbz/MSH0/2/DyJifY39izBlDngaOBYJcI3+uyh57304dAQKWrJ9ODStjvUJrjXTxbUGuxazbpnYmtwBjoeDUAAxYh6P7+3scNvXf6iUOnsLhUvbd26IorpED0LbtUyLCFvfBJ4V161ckOQBji0GpnaQxC7Ht/2MrnbFmNy51Tg7AmJAkAzAW58jLwRbVuq6xbj8YkNlVAOAjVFXlugnGpXNPeje5BbC9ZGMWsE2kEHf2Dtplp5VY6xh6Zq1sTtKqw0ssANi2KZSbE+ggWwCw0QnMm0J7ktw0DOwiABwCQCvxs7AAqMympFBOSRQuvd+2aTDZhVOSKBsAtmziTB4scVX86v2hIFfIpe259VovxwYA22MGk0OlzgSGlro5BH/YAmCtALJ6/jcllOgHDDmALjuaQ/TuKd9gZQG2+AIspkxTBLpm/n/LUeQ09rNzAteFO5DVwyqlegyEDanuyVf+hurNzgKsAij9BE9uY+c2CPoLXNbxQzILu4AWSwAg3IFFIhFWYKj3c/Zh2AKwYVbA3hfoZzpzt1ysAQAE/QMfOPemAc8/+G7mMf/D9f/sARiAACuHOHSR1Z091vQjzX21gZW98iFbEQD0ISCir1VVvXSlPeb7vRPNRShfFAD9GAGnk7jXTzTnONffBr4YC7BqBMbZruuQ3/eAAwQr5dup3guX1PWYFmnqt8UBYOME2ISJSNtzDAdFUeDCpkV9Ahu2xi0mOKZm8KyiqUpI+Z5IAHrW4ALWQGv9cqneZ739L7bX45CqyQdWpFS2mEigq5Cwl0Ap9c7eJhbtMsfVJZW4HQy/x+3gZ1e5iXMCxxpoo4fI+sU+vGAgrN1Oegz/g+vlD2Py2VkL0G8YNmMieePg4OCOiB4YY3CErPPTNM1zrfXP+/v7w4ODgxuOsXznRvUKiPYBpjYeQCil7qY6irbHH+6iwvsy2wsApoKyj+9lAPZR62ttzgBkAPZcAnve/GwBMgB7LoE9b362ABmAPZfAnjefhQWwu2mwsrc6egWBm8Gj4bhnCW05+BI7gm+JCIkv+LuaGpiKyWgyAGy07RSXPbncFiIYgCE9AgQsa1+mgmFxAOypW2e462fODaFc8uqHtOlx+RXWLC6KosAC1qK5A4sC0LbtWyI6n6P4lcA5HKy0ySSPHXg1wZQj9+FjWZbvJ7wb5JVFALA9AxdCe5+Jw3mfvcftZ31lYmjALqfo18pFB8Ae/IAbQQ+DIKtU8jP2N7WjaZo5t59t+hyGBdwwGvW28agAxLoKnuPBUSMHQs1mP/Yu42gAxFI+JMnx2JiYl1XGhCAKADGVb7vSrTHmeHa3ilDQ5+7jKdWJBUFwAKzDh/NxQ435g/KJJZApyui/E7P3r/0WZgi4Mi+oYxgcgMCO0DZ9sEgX33AYxByOppQJ7gAHBWDs5O8pLXR5h0OOYC8n0KX6s94NPQ0OBoD1gjENimr6+1JLORQsZPr7TYblQ3Z0kIhhMAACBkGce0aK6GCAqJ9zO1cFQlqBIAAsPA4OCe4O2TpLJWxY5SOyuai16zmExyEWkIIAkMgU/gbCEsNB27ZnRITTzZM+odoaBIAFPf9RocfKFu5lA4/WY4EXgswIvAGIFQL1FCBSxc+NMZee3/lV3PZ63CuYyuQPNiPEjSPeACwQ9fPRIc4TgrnG7hsnr9mmk2GXEpavo15cObeBIZxfbwBSev+OgrshIlwfj78f/YiajWA+tFfD4Up376Vrx/o5vx5iNhACgK0XPzq3KhdwkYD38bMhAEAuPksT6SJJoe96L4qFAGDK9e9C5cu/2r6bZDMA/HW8tYYZAOEK9K1+BsBXgsLLZwCEK9C3+hkAXwkKL58BEK5A3+pnAHwlKLx8BkC4An2rnwHwlaDw8hkA4Qr0rX4GwFeCwstnAIQr0Lf6GQBfCQovnwEQrkDf6mcAfCUovHwGQLgCfaufAfCVoPDyGQDhCvStfgbAV4LCy2cAhCvQt/oZAF8JCi+fARCuQN/qZwB8JSi8fAZAuAJ9q58B8JWg8PIZAOEK9K1+cgDqusbBxo98G5LLu0uAiL5XVeWVxRwiNQz592fu1c8lAkjgkzEG5xfMfrwBYHpCyGyBSCoY4tBsbwAgMEGHREjS71hdvXs/fiAIAPhQ9gXG9BXu/yHG/lVtggGQLUE4BY98KUjPjwIAPmp9gnN71k6eHQTgAj3enm2E+4ScDrsa+/l/AYMEc8w7AV3dAAAAAElFTkSuQmCC" >

**Comment by toniginard** [comment]
El giny ja està implementat
